version: '3'
services:
  database:
    build: .
    ports:
      - "6379:6379"
    image: "redis:5.0.5"
    networks:
      - my-network

  web:
    build: .
    ports:
      - "5000:5000"
    image: "samuelhornby/n3"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge