version: '3'
services:
  database:
    container_name: redis_database_1
    build: .
    ports:
      - "6379:6379"
    image: "redis:5.0.5"
    networks:
      - my-network

  web:
    container_name: api_web_server_1
    build: .
    ports:
      - "5000:5000"
    image: "samuelhornby/n3:dc"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge